apiVersion: v1
kind: Service
metadata:
  name: kubern8sservice
  labels:
    app: mariodb
spec:
  ports:  
  - port: 80
    targetPort: 80
  selector:
    app: mariodb
  type: LoadBalancer
  loadBalancerIP: IP_ADDRESS
